### PR TITLE
Don't treat requirement as pinned if version specifier ends in .*

### PR DESCRIPTION
**Pull request by eagle-r**
This handles #223 

I'm not able to get the tests running locally on my mac and I'm not sure how to generate suitable test packages in order to create an associated test.

If you can help in any way it would be much appreciated

### CODE REVIEW

**Comment by asottile** [comment]
yep! I can help you with this :D

there's a few packages in `./tests/testing/packages`

the tests are a little overwhelming to run, though they get run through [tox](https://tox.readthedocs.io/en/latest/) -- to run a specific test you can use `tox -e py37 -- tests/unit/simple_test.py` (for example)

bummer that the tests are failing on macos, I bet there's something in the testsuite expecting GNU :S

I'll sketch out a test for you tomorrow (if you don't get to it before me), there's a `many-versions-package` that gets built as a fixture, I think you can probably use `many-version-package==2.*,many-versions-package==2.1` and install `many-versions-package==2.0` before that to reproduce your situation

**Comment by eagle-r** [comment]
Thanks @asottile.

The initial `make test` failed because `readline` on mac doesn't work with the `-f` flag. Once I got that sorted, I had 47 tests error and 2 fail and it all seems to be related to issues with `capture_subprocess` which I haven't had time to investigate

**Comment by eagle-r** [comment]
Thanks for the help and the test!

Do you know when this might be released so I can let my boss know?

**Comment by chriskuehl** [comment]
I can make a new release now.

**Comment by chriskuehl** [comment]
Released v3.2.2, thanks for the bug report and patch!

**Comment by eagle-r** [comment]
Thanks greatly!

**Pull request merged**
