### PR TITLE
Pin argparse less meybs?

### LINKED ISSUE #47: double requirement: argparse==1.2.1
argparse is required in my requirements.txt, and `pip wheel` gets mad and stops.

    Double requirement given: argparse==1.2.1 (from -r requirements.txt (line 5)) (already in argparse==1.2.1, name='argparse')

Of course, I can take it out for the moment

### PR DESCRIPTION
**Pull request by asottile**
This might fix #47, I'm also running into a similar issue and working around it for now

### CODE REVIEW

**Comment by bukzor** [comment]
I did this to simplify the test suite. I think you'll find it doesn't pass.

**Comment by asottile** [comment]
I imagined the same, I can't get the tests to run locally on master either however

**Comment by bukzor** [comment]
That sounds like a bug, but I can't debug "doesn't work".

**Comment by asottile** [comment]
Lots and lots of "Unexpected third case" even after `rm -rf $VIRTUAL_ENV/local`

**Comment by bukzor** [comment]
You're definitely running into the noted bug.
The local to remove is the one under .tox/py27.

**Comment by asottile** [comment]
Tried that as well, I guess I'll just run with coverage off for now...

**Comment by bukzor** [comment]
how come

**Pull request merged**
