### PR TITLE
rm -rf local after ensuring a virtualenv

### LINKED ISSUE #167: Perhaps venv-update should rm -rf $venv/local ?
I find that we tend to do this anyway in each of our projects, perhaps we should just do it here?

### PR DESCRIPTION
**Pull request by asottile**
Resolves #167

### CODE REVIEW

**Comment by asottile** [comment]
ugh, travis still runs precise which has this bug.  Do we select trusty?

**Comment by asottile** [comment]
I'm going to abandon this for now, thought it was simple

**Comment by chriskuehl** [comment]
@asottile why not just switch to using trusty in Travis? Are we worried about actually breaking precise and below?

**Comment by asottile** [comment]
I forget whether I tried trusty, I have a sneaking suspicion I did but can't recall.  I think I gave up because getting pypy to work with `dist: trusty` is a ["fun time"](https://github.com/Yelp/venv-update/commit/b396b5fc10fe660bdeec6f1b7434ad15d14406d6)

it may just work now

**Pull request closed without merging**
