### PR TITLE
venv-update supports pip 18.1+

### LINKED ISSUE #214: Incompatible with pip 18.1
```
$ pip-faster install astpretty
Traceback (most recent call last):
  File "/tmp/h/venv/bin/pip-faster", line 11, in <module>
    sys.exit(main())
  File "/tmp/h/venv/lib/python3.6/site-packages/pip_faster.py", line 465, in main
    with pipfaster_packagefinder():
  File "/tmp/h/venv/lib/python3.6/site-packages/pip_faster.py", line 448, in pipfaster_packagefinder
    from pip._internal import basecommand
ImportError: cannot import name 'basecommand'

$ pip install 'pip<18.1'
Collecting pip<18.1
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-18.0

$ pip-faster install astpretty
Collecting astpretty
  slow: full search for unpinned requirement astpretty
  Downloading https://files.pythonhosted.org/packages/e3/61/16a1e2e2bf6270513d90695ad0d442a3521ab790562901288ef272fdc91a/astpretty-1.4.0-py2.py3-none-any.whl
Installing collected packages: astpretty
Successfully installed astpretty-1.4.0
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

### PR DESCRIPTION
**Pull request by asottile**
Resolves #214

### CODE REVIEW

**Comment by asottile** [comment]
probably WIP, let's see what the test suite says

**Comment by ssbarnea** [comment]
Something is really wrong if venv-update is ceiling pip version in such way because it will downgraded pip soon and break things.

Having this pinning on pip is similar to inclusion of a time-bomp. 

This patch is only buying some time, likely a couple of weeks.

**Comment by asottile** [comment]
If you understand how venv update / pip faster work this should not surprise you in the least

**Comment by ssbarnea** [comment]
Can we consider venv-update unmaintained? After 3 months this breaking bug is not yet fixed. Sadly I am forced to disable the tox-pip-extensions plugin from tox in order to avoid being hit by this bug.

**Comment by asottile** [comment]
3 months is a bit aggressive, this just isn't a priority for me. It should still work without this patch just you won't have absolutely the latest pip. Are you seeing crashes?

**Comment by asottile** [comment]
@chriskuehl I'll need you to make a release it seems

**Pull request merged**
