### PR TITLE
let's use master

### PR DESCRIPTION
**Pull request by bukzor**
It was defaulted to version 1.1.2 before

### CODE REVIEW

**Comment by chriskuehl** [comment]
Can we just delete this script? #176

**Comment by asottile** [comment]
+1 to deleting this script.  As a replacement I suggest putting a curl command in the README and adding that to release instructions

**Comment by striglia** [comment]
Hit this issue today, thumbs up to making the README reflect reality

**Comment by bukzor** [comment]
Can do that, but there's really no reason to leave it broken for the moment.

**Pull request merged**
