### PR TITLE
Configurable install deps

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by bukzor** [comment]
CI says it's broken.

**Comment by bukzor** [comment]
In all other respects, LGTM.

**Comment by asottile** [comment]
How do I fix the ci? Make test passes locally for me and I can't find the strings it mentions anywhere

**Comment by bukzor** [comment]
It smells like a stale pyc file. This import is getting the old value:

```
tests/functional/args.py:from venv_update import __doc__ as HELP_OUTPUT
```

On the other hand, how is the cli not getting that old value too?

The nice thing about circleci is you can ssh in. Set up an account and have a look.

**Comment by asottile** [comment]
Fixd

**Pull request merged**
